md_vars:
  global:
    repo_name: manga-g
    project_name: MangaG
    formal_name: Manga-G
    site: manga-g.pages.dev
    organization: manga-g
    user: 4cecoder
    dc_acc: 4ce#6574
    year: 2022
    workflow: Go
    workflow_file: go.yml
    desc: |-
      An awesome CLI program to read Manga via Terminal!
    long_desc: |-
      An awesome CLI program to read Manga via Terminal!

docs:
  input: raw_docs
  op: docs

rules:
  del:
  repl:
    'src="https://${site}/assets':
      - 'src="/assets'
    "src='https://${site}/assets":
      - "src='/assets"
    "](https://${site}/assets":
      - "](/assets"

requirements:
  dev: dev_req.txt

env:
  dev:
    req:
      - dev

license:
  year: 2022
  type: MIT
  cholder: {}