md_vars:
  global:
    project_name: MangaG
    repo_name: manga-g
    formal_name: Manga-G
    site: mg.test.whinyaan.xyz
    scripts_url: mg.test.whinyaan.xyz/scripts
    organization: 4cecoder
    user: 4cecoder
    dc_acc: 4ce#6574
    dc_link: 918988165379928135
    dc_inv: JbAtUxGcJZ
    mail_acc: whinyaan@pm.me
    mail_link: mailto:whinyaan@pm.me
    desc: |-
      An awesome CLI program to read Manga via Terminal!
    long_desc: |-
      An awesome CLI program to read Manga via Terminal!

docs:
  input: raw_docs
  op: docs

rules:
  del:
  repl:
    'src="https://${site}/assets':
      - 'src="/assets'
    "src='https://${site}/assets":
      - "src='/assets"
    "](https://${site}/assets":
      - "](/assets"

requirements:
  dev: dev_req.txt

env:
  dev:
    req:
      - dev

license:
  year: 2022
  type: MIT
  cholder: {}